CREATE TABLE IF NOT EXISTS obt_current_weather
(
    temp REAL,
    temp_min REAL,
    temp_max REAL,
    feels_like REAL,
    pressure INTEGER,
    humidity INTEGER,
    wind_speed REAL,
    wind_deg INTEGER,
    wind_gust REAL,
    last_hour_rain REAL,
    last_hour_snow REAL,
    cloudiness INTEGER,
    visibility INTEGER,
    condition_code INTEGER,
    condition_name TEXT,
    condition_description TEXT,
    location_code INTEGER,
    location_name TEXT,
    location_longitude REAL,
    location_latitude REAL,
    date DATE,
    year INTEGER,
    month INTEGER,
    month_name TEXT,
    day INTEGER,
    day_of_year INTEGER,
    weekday_name TEXT,
    calendar_week INTEGER,
    weekend TEXT
)
